# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e738cf6525128081db2292e87bd1063599a8b25864073eb6c044e3dc14528d6f00a36e4c1328e12f819bf2a39e176adb26ab5f391c17b2be49bb2e0e569ba39

test:
  secret_key_base: 2356e79cfe8c05d01bb1b62b8419d164a3d17182dedcb239ce0ab2d4e503312046bf316f6ece0b4dc13d5be49137364f1edfd5388f37182c041109dba16a07df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
